In [1]:
#from numpy import * #this is bad practice because it downloads all numpy functions and stores in your memory
import numpy as np #gives numpy the alias np and allows you to call numpy each time you want to use a function

In [2]:
a = np.zeros((3)) #create an array of 0s
a

array([ 0.,  0.,  0.])

In [3]:
b = np.ones((2,3)) #create 2 elements, each containing 3 ones, as floats (.)
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [4]:
c = np.random.randint(1,10,(2,3,4)) #create a matrix of random integers between 1 and 10
#matrix shape is 2 elements, each with 3 elements, each containing 4 elements
c

array([[[8, 8, 9, 2],
        [9, 3, 6, 3],
        [8, 4, 4, 3]],

       [[3, 9, 8, 9],
        [5, 4, 6, 6],
        [9, 2, 3, 7]]])

In [5]:
d = np.arange(0,11,1) #create array of numbers 0-10 with step 1
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
f = np.linspace(1,10,20) #create array of 20 numbers equally spaced between 1 and 10
#use when you don't want to do the maths to figure out the step sizes
f

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])

In [7]:
np.linspace(1,10,10)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [8]:
e = np.empty(3) #create an array with empty space - would use in place of zeroes function for performance purposes
e

array([ 0.,  0.,  0.])

In [9]:
a,b,c #this prints the arrays in order, separated by commas

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[8, 8, 9, 2],
         [9, 3, 6, 3],
         [8, 4, 4, 3]],
 
        [[3, 9, 8, 9],
         [5, 4, 6, 6],
         [9, 2, 3, 7]]]))

In [10]:
a = np.array([20,30,40,50])
b = np.arange(4)
a,b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [11]:
c = a-b
c
#note that a and b have to be the same shape to do this operation

array([20, 29, 38, 47])

In [12]:
b, b**2, b**3

(array([0, 1, 2, 3]), array([0, 1, 4, 9]), array([ 0,  1,  8, 27]))

In [13]:
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [14]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [15]:
a = np.arange(10)**3
print(a)

a[:6:2] = -1000 #starting at position 0 ending at position 6, exclusive, set every 2nd element to -1000
                #equivalent to [0:6:2]
                #using [] to select data is called slicing
print(a)

print(a[::-1])  #prints reverse

[  0   1   8  27  64 125 216 343 512 729]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]


In [16]:
a[:6:2] = np.arange(5,8)
print(a)

[  5   1   6  27   7 125 216 343 512 729]


In [17]:
a = np.arange(9).reshape(3,3)**3
a

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]])

In [18]:
print(a[::-1]) #print the elements in the reverse order

[[216 343 512]
 [ 27  64 125]
 [  0   1   8]]


In [19]:
print(a.flat[::-1]) #flatten the elements into one list and print in reverse

[512 343 216 125  64  27   8   1   0]


In [20]:
print(a.flat[::-1].reshape(3,3))

[[512 343 216]
 [125  64  27]
 [  8   1   0]]


In [22]:
b = np.random.randint(1,100,(4,4))

In [23]:
b

array([[45, 44, 63,  7],
       [99, 41, 49, 54],
       [84, 16, 46, 89],
       [53, 96, 13,  2]])

In [24]:
print(b[2,3])

89


In [25]:
print(b[0,0])

45


In [26]:
print(b.min())

2


In [27]:
print(b.max())

99


In [28]:
print(b.sum())

801


In [29]:
print(b[1,:].max()) #maximum of the row with index 1 i.e. the second row

99


In [30]:
print(b[:,3].min()) #minimum of the column with index 3 i.e. the fourth column

2


In [31]:
b[0:3,1] #of rows with index 0,1 and 2, bring back element index 1

array([44, 41, 16])

In [32]:
import pandas as pd

In [33]:
import matplotlib.pyplot as plt
%matplotlib inline

In [34]:
dates = pd.date_range('20140101',periods=6) #by default the period is days
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

## press shift and tab to bring up function information

In [45]:
pd.date_range('20140101',end='20141201',freq='MS') #MS is month start

DatetimeIndex(['2014-01-01', '2014-02-01', '2014-03-01', '2014-04-01',
               '2014-05-01', '2014-06-01', '2014-07-01', '2014-08-01',
               '2014-09-01', '2014-10-01', '2014-11-01', '2014-12-01'],
              dtype='datetime64[ns]', freq='MS')

In [46]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index=df.index,columns=df.columns)
df

A         B         C         D
2014-01-01 -1.002766 -0.802672 -1.149056 -0.810787
2014-01-02 -0.204136 -0.133818 -0.530600 -0.566190
2014-01-03 -0.778137 -0.988602 -1.337843 -0.647066
2014-01-04  0.426323  1.199537  0.125834  0.292322
2014-01-05  1.304605 -0.649955 -0.758863  0.060119
2014-01-06  0.225417  0.703662  0.184620 -0.102321

In [47]:
df.T

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A   -1.002766   -0.204136   -0.778137    0.426323    1.304605    0.225417
B   -0.802672   -0.133818   -0.988602    1.199537   -0.649955    0.703662
C   -1.149056   -0.530600   -1.337843    0.125834   -0.758863    0.184620
D   -0.810787   -0.566190   -0.647066    0.292322    0.060119   -0.102321

In [51]:
df2 = pd.DataFrame({'A':1.
                   ,'B':pd.Timestamp('20130102')
                   ,'C':pd.Series(7,index=list(range(4,8)),dtype='float32')
                   ,'D':np.array([3]*4,dtype='int32')
                   ,'E':'foo'})
df2

A          B    C  D    E
4  1.0 2013-01-02  7.0  3  foo
5  1.0 2013-01-02  7.0  3  foo
6  1.0 2013-01-02  7.0  3  foo
7  1.0 2013-01-02  7.0  3  foo

In [53]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

In [55]:
df2.head(1)

A          B    C  D    E
4  1.0 2013-01-02  7.0  3  foo

In [56]:
df.tail()

A         B         C         D
2014-01-02 -0.204136 -0.133818 -0.530600 -0.566190
2014-01-03 -0.778137 -0.988602 -1.337843 -0.647066
2014-01-04  0.426323  1.199537  0.125834  0.292322
2014-01-05  1.304605 -0.649955 -0.758863  0.060119
2014-01-06  0.225417  0.703662  0.184620 -0.102321

In [57]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [59]:
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [61]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.004782 -0.111975 -0.577651 -0.295654
std    0.847010  0.885524  0.634885  0.440842
min   -1.002766 -0.988602 -1.337843 -0.810787
25%   -0.634637 -0.764493 -1.051507 -0.626847
50%    0.010640 -0.391887 -0.644732 -0.334256
75%    0.376097  0.494292 -0.038275  0.019509
max    1.304605  1.199537  0.184620  0.292322

In [64]:
df.sort_values(by='B')

A         B         C         D
2014-01-03 -0.778137 -0.988602 -1.337843 -0.647066
2014-01-01 -1.002766 -0.802672 -1.149056 -0.810787
2014-01-05  1.304605 -0.649955 -0.758863  0.060119
2014-01-02 -0.204136 -0.133818 -0.530600 -0.566190
2014-01-06  0.225417  0.703662  0.184620 -0.102321
2014-01-04  0.426323  1.199537  0.125834  0.292322

In [67]:
df2['F'] = [2,2,4,4]
df2['G'] = [1,3,6,2]

In [68]:
df2

A          B    C  D    E  F  G
4  1.0 2013-01-02  7.0  3  foo  2  1
5  1.0 2013-01-02  7.0  3  foo  2  3
6  1.0 2013-01-02  7.0  3  foo  4  6
7  1.0 2013-01-02  7.0  3  foo  4  2

In [69]:
df2.sort_values(by=['F','G'])

A          B    C  D    E  F  G
4  1.0 2013-01-02  7.0  3  foo  2  1
5  1.0 2013-01-02  7.0  3  foo  2  3
7  1.0 2013-01-02  7.0  3  foo  4  2
6  1.0 2013-01-02  7.0  3  foo  4  6

In [72]:
del df2['F']
del df2['G']
df2

A          B    C  D    E
4  1.0 2013-01-02  7.0  3  foo
5  1.0 2013-01-02  7.0  3  foo
6  1.0 2013-01-02  7.0  3  foo
7  1.0 2013-01-02  7.0  3  foo

In [78]:
df[['A','B']]

A         B
2014-01-01 -1.002766 -0.802672
2014-01-02 -0.204136 -0.133818
2014-01-03 -0.778137 -0.988602
2014-01-04  0.426323  1.199537
2014-01-05  1.304605 -0.649955
2014-01-06  0.225417  0.703662

In [84]:
df[0:2][['A','B']]

A         B
2014-01-01 -1.002766 -0.802672
2014-01-02 -0.204136 -0.133818

In [85]:
df[0:2][df.columns[:2]]

A         B
2014-01-01 -1.002766 -0.802672
2014-01-02 -0.204136 -0.133818

In [88]:
df.loc[dates[0:2]]

A         B         C         D
2014-01-01 -1.002766 -0.802672 -1.149056 -0.810787
2014-01-02 -0.204136 -0.133818 -0.530600 -0.566190

In [89]:
df.loc[dates[0]]

A   -1.002766
B   -0.802672
C   -1.149056
D   -0.810787
Name: 2014-01-01 00:00:00, dtype: float64

In [87]:
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [90]:
df.loc[:,['A','B']]

A         B
2014-01-01 -1.002766 -0.802672
2014-01-02 -0.204136 -0.133818
2014-01-03 -0.778137 -0.988602
2014-01-04  0.426323  1.199537
2014-01-05  1.304605 -0.649955
2014-01-06  0.225417  0.703662

In [91]:
df.loc['20140102':'20140104','B']

2014-01-02   -0.133818
2014-01-03   -0.988602
2014-01-04    1.199537
Freq: D, Name: B, dtype: float64

In [92]:
df.iloc[3:]

A         B         C         D
2014-01-04  0.426323  1.199537  0.125834  0.292322
2014-01-05  1.304605 -0.649955 -0.758863  0.060119
2014-01-06  0.225417  0.703662  0.184620 -0.102321

In [94]:
df[df.A<0]

A         B         C         D
2014-01-01 -1.002766 -0.802672 -1.149056 -0.810787
2014-01-02 -0.204136 -0.133818 -0.530600 -0.566190
2014-01-03 -0.778137 -0.988602 -1.337843 -0.647066

In [96]:
df2[df2.D==3]

A          B    C  D    E
4  1.0 2013-01-02  7.0  3  foo
5  1.0 2013-01-02  7.0  3  foo
6  1.0 2013-01-02  7.0  3  foo
7  1.0 2013-01-02  7.0  3  foo

In [98]:
df.A<0

2014-01-01     True
2014-01-02     True
2014-01-03     True
2014-01-04    False
2014-01-05    False
2014-01-06    False
Freq: D, Name: A, dtype: bool

In [99]:
df_posA = df.copy()
df_posA[df_posA.A<0] = -1*df_posA
df_posA

A         B         C         D
2014-01-01  1.002766  0.802672  1.149056  0.810787
2014-01-02  0.204136  0.133818  0.530600  0.566190
2014-01-03  0.778137  0.988602  1.337843  0.647066
2014-01-04  0.426323  1.199537  0.125834  0.292322
2014-01-05  1.304605 -0.649955 -0.758863  0.060119
2014-01-06  0.225417  0.703662  0.184620 -0.102321

In [100]:
df

A         B         C         D
2014-01-01 -1.002766 -0.802672 -1.149056 -0.810787
2014-01-02 -0.204136 -0.133818 -0.530600 -0.566190
2014-01-03 -0.778137 -0.988602 -1.337843 -0.647066
2014-01-04  0.426323  1.199537  0.125834  0.292322
2014-01-05  1.304605 -0.649955 -0.758863  0.060119
2014-01-06  0.225417  0.703662  0.184620 -0.102321

In [101]:
df[(df.A<0)&(df.B<0)]

A         B         C         D
2014-01-01 -1.002766 -0.802672 -1.149056 -0.810787
2014-01-02 -0.204136 -0.133818 -0.530600 -0.566190
2014-01-03 -0.778137 -0.988602 -1.337843 -0.647066